### ISSUE TITLE
"make tests" compile fails 

### ISSUE THREAD

**Issue by patbohn** [nodrogluap/OpenDBA#11]
Hi, 
this tool looks really interesting to use. I stumbled across one issue however during the install, and that is, while "make" finished successfully, "make tests" fails with the following errors:

`$ make tests
nvcc -DDEBUG=0 -DDOUBLE_UNSUPPORTED=0 -DHDF5_SUPPORTED=0 --expt-relaxed-constexpr -rdc=true -maxrregcount 26 --std=c++11 -arch=sm_61 -c tests/openDBA_test.cu -o tests/openDBA_test.o
tests/openDBA_test.cu(79): error: no instance of function template "setupAndRun" matches the argument list
            argument types are: (char *, char **, int, char *, int, int, int, int, int)

tests/openDBA_test.cu(122): error: no instance of function template "setupAndRun" matches the argument list
            argument types are: (char *, char **, int, char *, int, int, int, int, int)

tests/openDBA_test.cu(166): error: no instance of function template "setupAndRun" matches the argument list
            argument types are: (char *, char **, int, char *, int, int, int, int, int)

tests/openDBA_test.cu(215): error: no instance of function template "setupAndRun" matches the argument list
            argument types are: (char *, char **, int, char *, int, int, int, int, int)

tests/openDBA_test.cu(268): error: no instance of function template "setupAndRun" matches the argument list
            argument types are: (char *, char **, int, char *, int, int, int, int, int)

5 errors detected in the compilation of "/vol/tmp/tmpxft_00006227_00000000-6_openDBA_test.cpp1.ii".
make: *** [Makefile:41: tests/openDBA_test.o] Error 1`

I am compiling this on a Linux Fedora (29) machine with cuda-10.2 as CUDA_HOME.

**Comment by nodrogluap** [comment]
Function prototype issue now fixed, closing.
