### ISSUE TITLE
Compilation issue with `make tests`

### ISSUE THREAD

**Issue by liam-mitchell21** [nodrogluap/OpenDBA#14]
Hello, 

When I clone the repo, make works fine, but make tests seems to run into a linking problem.
![Problem in question](https://user-images.githubusercontent.com/32913648/173269515-aa341bf5-7ebf-478f-90f5-8a1fe57b7123.png)

I tried fiddling around with the include lines inside io_test_utils.cu, but changing the includes paths resulted in 'no such file or directory' errors, so it seems that io_test_utils.cu can see the included io_utils.hpp and cpu_utils.hpp fine, it just isn't importing the functions properly. 
I also tried appending export to the function definitions, and adding -x cu to the compiler call, but neither of these solved it. 

I'm not too familiar with C++, so it's likely I'm missing something simple, I look forward to learning what it is. 
--Liam

**Comment by nodrogluap** [comment]
The tests assume that you've compiled (make) with HDF5_SUPPORTED=1. This is probably a bad assumption, but not 100% sure how I'd ensure the same env setting was used for both make and make tests, unless I make them one target rather than two. Lemme think about that. In the meantime, can you confirm that if you run "make HDF5_SUPPORTED=1" on a clean version, that "make tests" then works.

**Comment by nodrogluap** [comment]
As a start, I've changed the README's Quick Start section to distinguish between how you use the make commands with and without HDF5 support (i.e. if you plan to use it for nanopore data or not).

**Comment by nodrogluap** [comment]
Commit to master dd826bf fixes assumption of HDF5 support. Tested with and without HDF5_SUPPORTED=1 flag in make command. Tentatively closing, feel free to reopen if this doesn't work in your hands.

**Comment by liam-mitchell21** [comment]
Yes, running
make HDF5_SUPPORTED=1 &&​
make HDF5_SUPPORTED=1 tests​
seemed to work fine, thanks for the help!

--Liam
________________________________
