### ISSUE TITLE
CUDA memory out

### ISSUE THREAD

**Issue by hasindu2008** [nodrogluap/OpenDBA#15]
Hi

Thank you for writing this great tool. Documentation was easy to follow and I get it compiled pretty easily. I attempted it with a relatively smaller dataset (12 multi-FAST5 files) and it ran successfully. 

Now I am trying to run on a relatively large dataset and I am getting the following error.
```
 ./openDBA fast5 float open_end output_prefix 0 /dev/null 1 ~/scratch/rna/na12878/fast5/Bham_Run1/*.fast5
Step 1 of 3: Loading 270 FAST5 data files, total sequence count 1076373
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%                                           .
..........................................................................\CUDA error: unknown error (Cannot allocate CPU memory for FAST5 signal)
```

Is there any option that I can control to reduce the GPU memory usage by any chance?

**Comment by nodrogluap** [comment]
Hi

Unfortunately, the short answer is no. It's already using managed memory (i.e. CPU memory that gets staged a page at a time to GPU on demand) to store the signals, so if you run out of memory there aren't really any other reasonably performant storage options. The first step after the loading is an all-vs-all DTW comparison, which for 1M sequences is a trillion DTW alignments, which might take several years even in this very fast implementation. The modus operandi for very large datasets is to process the FAST5 files independently or in small groups (lets say <50,000 reads each, to keep the all-vs-all stage reasonable but still capture transcript diversity), then run openDBA again on the consensus from all the first runs.

**Comment by hasindu2008** [comment]
Thanks for the response.  What I am interested in is creating a consensus for each transcript. If I do minimap2 on the basecalled reads onto the transcriptome, manually classify reads groups into based on which transcript each read maps to, run openDBA separately on each of those groups, will that be a sane approach?

**Comment by nodrogluap** [comment]
That is sane. :-)
