### ISSUE TITLE
Question on cluster_membership.txt format

### ISSUE THREAD

**Issue by wvdtoorn** [nodrogluap/OpenDBA#19]
Hi @nodrogluap,

Thank you for creating this amazing tool!

I am using OpenDBA to cluster sequences from a BLOW5 file. Could you maybe clarify the format of the cluster_membership.txt output file? 
To me, it looks like
```read_id_x, cluster_id, read_id_y```.
What is the relation between `read_id_x` and `read_id_y`? Which of the two is assigned to cluster `cluster_id`?

Thanks a lot!

**Comment by nodrogluap** [comment]
Hi,

The third column is the centroid read for the cluster # in the second cluster. It’s purely for convenience.

Paul

On Feb 3, 2023, at 3:34 PM, wvandertoorn ***@***.***> wrote:

﻿
[△EXTERNAL]



Hi @nodrogluap<https://github.com/nodrogluap>,

Thank you for creating this amazing tool!

I am using OpenDBA to cluster sequences from a BLOW5 file. Could you maybe clarify the format of the cluster_membership.txt output file?
To me, it looks like
read_id_x, cluster_id, read_id_y.
What is the relation between read_id_x and read_id_y? Which of the two is assigned to cluster cluster_id?

Thanks a lot!

**Comment by nodrogluap** [comment]
I should say more formally that the read_id_y is the initial *medoid* of the cluster # (secobnd column) to which read_id_x belongs. The final converged cluster *centroid* will be scaled to the read_id_x mean and standard deviation on output.

**Comment by wvdtoorn** [comment]
Thanks for the clarification!
