### ISSUE TITLE
Averaging nanopore signal reads

### ISSUE THREAD

**Issue by DBbatic** [nodrogluap/OpenDBA#2]
Hello,

I have been trying to find the average of 800 sequences with the average of 28 k points. I'm running openDBA on Titan Xp graphics card with 12G RAM. So far the process stops on the 3rd step (finding the centroid) with the error message saying GPU ran out of memory. I'm currently trying to subsample the number of points in the reads (taking every 6th point of each read didn't help). However, I would like to preserve as much points as possible.

Could you explain the memory complexity of each step and what would be the best approach to solve this problem? Furthermore, is there a possibility of using fastDTW in the algorithm to account for bigger data samples?

Here is the exact error message:
"CUDA error: out of memory (Allocating pitched GPU memory for sequence:centroid path matrix)"

**Comment by nodrogluap** [comment]
Will detail memory complexity shortly, but quickly: What are longest and shortest sequences, what is the length of the medoid, and are you using int, float, or double representation? Does it fail on round 1 of centroid generation? Immediately or part way through?

**Comment by DBbatic** [comment]
This is for subsampled reads (every 6th point is taken):
-> shortest sequence: 1402 points
-> longest sequence: 115596 (second longest is 12 000) points
-> I'm using float
-> medoid is 4013 points

Since there is a big difference between the longest read and all the other ones, I removed it, then ran the process again. It failed on iteration number 28 (without removing the longest read it failed on iteration 10). I think it fails at the start of iteration. I'll check when I rerun it again and update you.

**Comment by nodrogluap** [comment]
Thanks for the details.  I've identified a memory leak that would cause the refinement iterations to eventually run out of free memory with your kind of input data. Will try to roll this into an update after the holiday weekend. In the interim, can you set the convergence threshold to slightly above whatever you get as a delta for iteration 27, so it completes successfully?  I just want to make sure that once the leak is fixed, you don't run into any issue outputting the result after convergence. 😄

**Comment by DBbatic** [comment]
Hello,

I ran the program for both sub sampled and full data set again with convergence thresholds 0.20 and 0.32 respectively. Program finishes with no errors. However, the average signal I'm getting is very close to the straight line.

(the data is from sub sampled run -> similar results in the other run)

Minimum value: 594.608
Maximum value: 595.177
Number of points: 4013

I even took a look at the file's values:
-> 2439 of them are 594.909
-> 1531 of them are 594.910

which is 3970 / 4013 points.

I have plotted some of the signals when I first started working with the files and I wouldn't expect these results from the data I have. I can send you the data I'm using since there can always be something I overlooked. 

P.S. the program breaks at the start of the iteration.

**Comment by nodrogluap** [comment]
Yes, please send your data to gordonp@ucalgary.ca so I can see what’s going on. Sub sampling is generally a bad idea with noisy nanopore signals, and can lead to flatline averages so please send the full raw data.

**Comment by DBbatic** [comment]
I sent the files. Sorry for late responses. I'm occupied with another project at the moment. Thank you for helping me out.

**Comment by nodrogluap** [comment]
Have committed a couple of small memory fixes (including ironically in the cleanup thread), please see if that helps.  A larger commit of a move to managed memory and assorted other changes will take a few weeks more as I'm going to be away.

**Comment by agosztolai** [comment]
Thank you. I am still facing the same problems as before. I noticed that I have a few time series that do not change but stays constant over time. 

Perhaps this causes some issues with the internal normalisation due to division by zero? Just guessing.

If I normalise first and then run on the normalised sequences then the algorithm does not proceed to the iteration phase.

Can you help with this?

```
(base) gosztolai@SV-87:/data/AG/Berman_data$ /home/gosztolai/Dropbox/github/time_series_analysis/OpenDBA/./openDBA tsv float global test 0.01 epochs_dim0.txt
Step 1 of 3: Loading 1 TSV data file, total sequence count 503
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
|...................................................................................................|
Devices found: 2
Maximum of 1024 threads per block on device 0
Step 2 of 3: Finding medoid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
Initial medoid (base) 
```

**Comment by nodrogluap** [comment]
Latest commit eliminates this late-convergence CUDA error by fixing a race condition between stream callback cleanup process and DTW path copy to CPU memory.
