### ISSUE TITLE
solution not converging

### ISSUE THREAD

**Issue by agosztolai** [nodrogluap/OpenDBA#3]
Hello, 

thanks for developing this potentialy very useful code.

I would like to use your script to obtain the DTW distance matrix (7-8000) relatively short (10-100 timepoints) time series of different lengths

I have been using the following command
`/OpenDBA/./openDBA tsv int global /data/DTW_res 0.05 /data/block_1.txt`

The file block_1.txt is a tab separated file with every line is a time series and the first column is a number.

For example: line 1 and 2 are 
```
0	148	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	147	148	148	148	148	147	147	147	148
0	149	148	148	149	148	148	148	148	149	148	148	148	148	148	149	149	148	148	148	148	147	148	148	148	148	148	148	148	149	148	148	147	147	147	147	147	147	147	147	147	147	147	148	147	147	147	147
```

However, so far I have not succeeded in obtaining a converged solution.

This the error message I get when I try to run 100 time series at once. 

```
New delta is 2.16918e+07

Step 3 of 3 (round 370 of max 1000 to find delta < 0.5): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
......................................................................|CUDA error: out of memory (Allocating page locked CPU memory for DTW stream callback data)
```
The delta seems very large (given the tolerance value of 0.05) and does not seem to be decreasing with the iterations. 

If I try to run all the 8000 time series at once I get this message at step 3-4 or so. However, i that case the delta is much smaller.

Could you please help with finding what the problem is? Also could you provide an example input file?

Adam

**Comment by agosztolai** [comment]
The error probably happened because I have not normalized the inputs sequences.

**Comment by nodrogluap** [comment]
Hi,

There is a small memory leak, the fix for which I have not yet committed, which should address the out of memory issues after so many rounds of convergence.  OpenDBA does the normalization for you, so no need for you to change your input. If you can provide me (gordonp ucalgary ca) your input, I can check it out.

**Comment by nodrogluap** [comment]
Merging to issue #2

**Comment by agosztolai** [comment]
Thank you, after I normalize manually, the iterations converge with  delta = 0 after one step, which is also strange perhaps? I will send you the input files in a few minutes. Thank you again for helping out.

**Comment by agosztolai** [comment]
Hi, could you please provide an input file that the algorithm works with? This would be very useful to see if I am doing something wrong.

For now I have tried changing the input size to make it much shorter. For example I pass only 100 sequences and the solution does not seem to be converging. So I am not convinced that the memory leak is the only issue. Unless my input file is wrong.

```
New delta is 66752

Step 3 of 3 (round 8 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
New delta is 354662

Step 3 of 3 (round 9 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
New delta is 354662

Step 3 of 3 (round 10 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
New delta is 109643

Step 3 of 3 (round 11 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
New delta is 66752

Step 3 of 3 (round 12 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................................................................................................|
New delta is 354662

Step 3 of 3 (round 13 of max 1000 to find delta < 0.05): Converging centroid
0%        10%       20%       30%       40%       50%       60%       70%       80%       90%       100%
....................\CUDA error: out of memory (Allocating page locked CPU memory for DTW stream callback data)
512
```
