### ISSUE TITLE
Normalisation problem

### ISSUE THREAD

**Issue by agosztolai** [nodrogluap/OpenDBA#4]
Hello, 

I have done some tests on your code and I have a strong suspicion that there is a bug with the normalisation.

In particular, if I provide a constant sequence, the code fails. I have tried with one of the examples in https://www.cs.ucr.edu/~eamonn/time_series_data_2018/ called FiftyWords_TEST.txt. It converges OK. However, when I change one of the lines (except the first column) to some constant value (e.g. 2.0 (tab) 2.0 (tab) 2.0) the code fails in step 3 and does not proceed to the iteration phase. When I change one of the values a little bit (e.g. 2.0 (tab) 2.0 (tab) 2.0001), it runs OK. 

This suggests that there is a division-by-zero problem in the Z-normalisation.

Could you fix this by adding an if statement or something to allow for occasional constant sequences?

Thank you!

**Comment by nodrogluap** [comment]
Thanks, a constant series would indeed be problematic! I’m away from the office for a few weeks, so won’t be able to push something out until I return, but if you want to make a pull request I’d be more than happy to accept.

On Nov 21, 2019, at 1:51 AM, Adam Gosztolai <notifications@github.com> wrote:

﻿

Hello,

I have done some tests on your code and I have a strong suspicion that there is a big with the normalisation.

In particular, if I provide a constant sequence, the code fails. I have tried with one of the examples in https://www.cs.ucr.edu/~eamonn/time_series_data_2018/ called FiftyWords_TEST.txt. It converges OK. However, when I change one of the lines (except the first column) to some constant value (e.g. 2.0 (tab) 2.0 (tab) 2.0) the code fails in step 3 and does not proceed to the iteration phase. When I change one of the values a little bit (e.g. 2.0 (tab) 2.0 (tab) 2.0001), it runs OK.

This suggests that there is a division-by-zero problem in the Z-normalisation.

Could you fix this by adding an if statement or something to allow for occasional constant sequences?

Thank you!

**Comment by agosztolai** [comment]
I’m sorry, I have no clue about CUDA so I cannot really help :(

However, that’s good news for me because I can have a workaround solution. 

I would also note that for large datasets (7-8000 sequences of length ~1-300) there still seems to be a memory issue as the GPU runs out of memory after 4-5 iterations. For smaller datasets this seems to be ok. 

I have seen that you planned some more memory management updates so I just wanted to flag the issue.

By the way, your code is a lifesaver. Thank you for putting in the effort.

Best wishes, 

Adam

**Comment by nodrogluap** [comment]
Latest commit fixes the error encountered when a constant data series (just one same value repeated over and over again) is used as an input.
