### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by rrazaghi** [nodrogluap/OpenDBA#5]
Hi Paul!
I'm running into this error when running OpenDBA on a dRNA run from a flongle flowcell:

`Chopping sequence prefixes
Maximum of 1024 threads per block on device 0
Segmenting with minimum acceptable segment size of 4
Processing 512 samples per threadblock with 256 threads, max 128 segments, grid (68693, 3061,1)
CUDA error: an illegal memory access was encountered (Synchronizing stream after sequence segmentation)`

Do you have any ideas why this is happening? I have a 32GB V100

**Comment by nodrogluap** [comment]
Hi,

That's a pretty generic error...can you send a minimal working example, i.e. the exact command line you use, and the data file so I can recreate? (I also have 32GB V100s)

**Comment by nodrogluap** [comment]
And the compiler flags you used, if any.

gordonp@ucalgary.ca

**Comment by nodrogluap** [comment]
This may have been caused by a 32-bit integer overflow when you input a large list of data to segment. I've committed a fix (change to 64-bit integer offset), please let me know if that helped then I can close this issue.

**Comment by nodrogluap** [comment]
Have tried multiple 4000ish input FAST5 file with no CUDA errors. Closing for now, but opening new issue #5 for slow performance when large input files are used on limited RAM GPUs.
